spring:
  cloud:
    gateway:
      routes:
        - id: tour-route
          uri: ${JPA_APP_URI}
          predicates:
            - Path=/tours/**
        - id: packages-route
          uri: ${JPA_APP_URI}
          predicates:
            - Path=/packages/**
        - id: tour-image-route
          uri: ${MONGO_APP_URI}
          predicates:
            - Path=/images/**
          filters:
            - PrefixPath=/api